window.SCHPLAY_GAMES = window.SCHPLAY_GAMES || {};
window.SCHPLAY_GAMES.list = [
    { name: "Deep Freeze", href: "games/deep-freeze.html", img: "images/deepfreeze.webp" },
    { name: "Doodle Jump", href: "games/doodlejump.html", img: "images/doodlejump.webp" },
    { name: "Dadish 1", href: "games/dadish-1.html", img: "images/dadish" },
    { name: "Dadish 2", href: "games/dadish-2.html", img: "images/dadish2.jpeg" },
    { name: "Dadish 3", href: "games/dadish-3.html", img: "images/dadish3.avif" },
    { name: "Doge Miner", href: "games/doge-miner.html", img: "images/dogeminer.jpeg" },
    { name: "EvoWars", href: "games/evowars.html", img: "images/evowars.jpeg" },
    { name: "There Is No Game", href: "games/there-is-no-game.html", img: "images/thereisnogame.jpg" },
    { name: "Bit Gun Io", href: "games/bit-gun-io.html", img: "images/bitgun.avif" },
    { name: "Steal Brainrot Online", href: "games/steal-brainrot-online.html", img: "images/stealbrainrot.avif" },
    { name: "Find the Alien", href: "games/find-the-alien.html", img: "images/findthealien.jpeg" },
    { name: "Magic Tiles 3", href: "games/magic-tiles-3.html", img: "images/magictiles3.jpeg" },
    { name: "Shovel 3D", href: "games/shovel-3d.html", img: "images/shovel3d.jpeg" },
    { name: "BuildNow GG", href: "games/buildnow-gg.html", img: "images/buildnow.jpeg" },
    { name: "Man Runner 2048", href: "games/man-runner-2048.html", img: "images/manrunner2048.png" },
    { name: "Mob Control", href: "games/mob-control.html", img: "images/mobcontrol.jpeg" },
    { name: "Stickman and Guns", href: "games/stickman-and-guns.html", img: "images/stickmanandguns.avif" },
    { name: "Duck Life 3", href: "games/duck-life-3.html", img: "images/ducklife3.webp" },
    { name: "Duck Life 5", href: "games/duck-life-5.html", img: "images/ducklife5.webp" },
    { name: "Duck Hunt", href: "games/duckhunt.html", img: "images/duckhunt.webp" },
    { name: "Duck Life 2", href: "games/ducklife2.html", img: "images/ducklife2.webp" },
    { name: "Dune Buggy", href: "games/dunebuggy.html", img: "images/dunebuggy.webp" },
    { name: "Electric Man 2", href: "games/electric-man-2.html", img: "images/electricman2.webp" },
    { name: "Fireboy and Watergirl Fire Temple", href: "games/fireboy-and-watergirl-firetemple.html", img: "images/fireboywatergirlfiretemple.webp" },
    { name: "Flappy 2048", href: "games/flappy-2048.html", img: "images/flappy2048.webp" },
    { name: "Flappy Bird", href: "games/flappy-bird.html", img: "images/flappybird.webp" },
    { name: "Bad Time Simulator", href: "games/bad-time-simulator.html", img: "images/badtimesimulator.webp" },
    { name: "Baldi's Basics Plus", href: "games/baldi-plus.html", img: "images/baldiplus.webp" },
    { name: "Bejeweled 2", href: "games/bejeweled2.html", img: "images/bejeweled2.webp" },
    { name: "Bloxors", href: "games/bloxors.html", img: "images/bloxors.webp" },
    { name: "Cat Mario", href: "games/catmario.html", img: "images/catmario.webp" },
    { name: "Civiballs 1", href: "games/civiballs1.html", img: "images/civiballs1-Gameplay2_thumb.jpg" },
    { name: "Club Penguin", href: "games/clubpenguin.html", img: "images/clubpenguin.webp" },
    { name: "Cookie Clicker Working 2026", href: "games/cookie-clicker-working-2026.html", img: "games/cookie-clicker/img/cookieShower1.png" },
    { name: "Curveball", href: "games/curveball.html", img: "images/curveball.webp" },
    { name: "Adastra", href: "games/adastra.html", img: "images/adastra.webp" },
    { name: "Antbuster", href: "games/antbuster.html", img: "images/antbuster.webp" },
    { name: "Arcade Wizard", href: "games/arcade-wizard.html", img: "images/arcadewizard.webp" },
    { name: "Bad Ice Cream 1", href: "games/bad-icecream-1.html", img: "images/badicecream1.webp" },
    { name: "Bad Ice Cream 2", href: "games/bad-icecream-2.html", img: "images/badicecream2.webp" },
    { name: "Bad Ice Cream 3", href: "games/bad-icecream-3.html", img: "images/badicecream3.webp" },
    { name: "Agar.io", href: "games/agario.html", img: "images/agario.webp" },
    { name: "Angry Birds Halloween", href: "games/angrybirdshalloween.html", img: "images/angrybirdshalloween.webp" },
    { name: "Ace Gangster", href: "games/acegangster.html", img: "images/acegangster.webp" },
    { name: "10 Minutes Till Dawn", href: "games/10-minutes-till-dawn.html", img: "images/10mintilldawn.webp" },
    { name: "1v1.lol", href: "games/1v1lol.html", img: "https://play-lh.googleusercontent.com/QYGRIDJbyVO7L7jH8CwiKJ4NumTGgcTVqU3ITooLWxro-eeNns1RZ0uwGGFe-r8M4co" },
    { name: "Slope", href: "games/slope.html", img: "images/slope.webp" },
    { name: "Slope 2", href: "games/slope2.html", img: "images/slope2.webp" },
    { name: "Retro Bowl", href: "games/retrobowl.html", img: "images/retrobowl.webp" },
    { name: "Block Blast", href: "games/blockblast.html", img: "images/blockblast.webp" },
    { name: "Blumgi Rocket", href: "games/blumgi-rocket.html", img: "images/blumgi-rocket.jpeg" },
    { name: "Idle Breakout", href: "games/idle-breakout.html", img: "images/idlebreakout.webp" },
    { name: "Gunspin", href: "games/gunspin.html", img: "images/gunspin.webp" },
    { name: "Learn To Fly", href: "games/learntofly.html", img: "games/learntofly/icon.png" },
    { name: "Learn To Fly 2", href: "games/learntofly2.html", img: "images/learntofly2.webp" },
    { name: "Learn To Fly 3", href: "games/learntofly3.html", img: "images/learntofly3.webp" },
    { name: "House Of Hazards", href: "games/houseofhazards.html", img: "images/houseofhazards.webp" },
    { name: "Hole.io", href: "games/holeio.html", img: "images/holeio.webp" },
    { name: "Cut The Rope", href: "games/cut-the-rope.html", img: "images/cuttherope.webp" },
    { name: "Tank Trouble", href: "games/tanktrouble.html", img: "images/tanktrouble.webp" },
    { name: "Drift Hunters", href: "games/drifthunters.html", img: "images/drifthunters.webp" },
    { name: "Draw The Hill", href: "games/draw-the-hill.html", img: "images/drawthehill.webp" },
    { name: "Getaway Shootout", href: "games/getaway-shootout.html", img: "images/getawayshootout.webp" },
    { name: "Crossy Road", href: "games/crossyroad.html", img: "images/crossyroad.webp" },
    { name: "Rooftop Sniper", href: "games/rooftopsnipers.html", img: "images/rooftopsnipers.webp" },
    { name: "Boxing Random", href: "games/boxingrandom.html", img: "images/boxingrandom.webp" },
    { name: "Adventure Capitalist", href: "games/adventurecapitalist.html", img: "images/adventurecapitalist.webp" },
    { name: "Hide & Smash", href: "games/hideandsmash.html", img: "images/hideandsmash.webp" },
    { name: "MonkeyMart", href: "games/monkey-mart.html", img: "images/monkeymart.webp" },
    { name: "Retro Bowl College FIXED!", href: "games/rb-college.html", img: "images/retrobowlcollege.webp" },
    { name: "Minecraft (Eagler)", href: "games/minecraft.html", img: "images/mc.webp" },
    { name: "Bloons TD5", href: "games/bloonstd5.html", img: "images/btd5.webp" },
    { name: "Mr Mine", href: "games/mrmine.html", img: "images/mrmine.webp" },
    { name: "Run 2", href: "games/run2.html", img: "images/run2.webp" },
    { name: "Run 3", href: "games/run3.html", img: "images/run3.webp" },
    { name: "Soundboard Unblocked", href: "games/soundboard.html", img: "games/soundboard-main/button.png" },
    { name: "Spend Elon's Money", href: "games/spending-elonmusk-money.html", img: "images/elonmusk.webp" },
    { name: "Plants V Zombies (Full)", href: "games/pvz.html", img: "images/pvz.webp" },
    { name: "Mine Sweeper", href: "games/minesweeper.html", img: "images/minesweeper.webp" },
    { name: "Pizza Tower", href: "games/pizzatower.html", img: "images/pizzatower.webp" },
    { name: "Pixel Gun", href: "games/pixelgun.html", img: "images/pixelgun.webp" },
    { name: "Google Snake", href: "games/googlesnake.html", img: "images/googlesnake.webp" },
    { name: "OVO", href: "games/ovo.html", img: "images/ovo.webp" },
    { name: "Basketball Stars", href: "games/basketballstars.html", img: "images/basketballstars.webp" },
    { name: "Stacktris", href: "games/stacktris.html", img: "images/stacktris.webp" },
    { name: "FNAF", href: "games/fnaf.html", img: "images/fnaf.webp" },
    { name: "Five Nights at Epstein", href: "games/five-nights-at-epstein.html", img: "images/Screenshot-2025-08-14-at-9.19.56-AM-854x675.webp" },
    { name: "DBZ Devolution", href: "games/dbz.html", img: "images/dbz.webp" },
    { name: "Deltarune", href: "games/deltarune.html", img: "games/deltarune-main/logo.png" },
    { name: "Drive Mad", href: "games/drivemad.html", img: "images/drivemad.webp" },
    { name: "Papa's Games", href: "games/papas-games.html", img: "images/papasgame.webp" },
    { name: "Stickman Games", href: "games/henry-stickman.html", img: "https://cdn2.steamgriddb.com/icon/9f61408e3afb633e50cdf1b20de6f466.png" },
    { name: "Vex's Games", href: "games/vex.html", img: "https://play-lh.googleusercontent.com/0OnVFzHIMuLLeMjvACoNzxRbungfOH1zH4hUWQnIg5KfM2va_mFssFuRGq26WqWA" },
    { name: "2048", href: "games/2048.html", img: "images/2048.webp" },
    { name: "Paper.io 2", href: "games/paperio2.html", img: "images/paperio2.webp" },
    { name: "1", href: "games/2048.html", img: "images/2048_logo.svg.png" },
    { name: "Subway Surfers", href: "games/subwaysurfer.html", img: "https://img.poki.com/cdn-cgi/image/quality=78,width=314,height=314,fit=cover,f=auto/81a0a3f18cf0ee129e56edb50fc52c3b.png" },
    { name: "Soccer Random", href: "games/soccer-random.html", img: "https://play-lh.googleusercontent.com/G1PIlb6HWKSaDre0XpUcmKGps9T4iamsSlwrogB3EJzYv4bz0M2am4D17MtGzndaOOU" },
    { name: "MotoX3M Games", href: "games/motox3m.html", img: "images/motocross.webp" },
    { name: "CSGO Case Opener", href: "games/csgo-clicker.html", img: "images/csgoclicker.webp" },
    { name: "Crossy Road", href: "games/crossyroad.html", img: "https://upload.wikimedia.org/wikipedia/en/7/71/Crossy_Road_icon.jpeg" },
    { name: "Temple Run 2", href: "games/templerun2.html", img: "https://play-lh.googleusercontent.com/go4XqS4mYs-G2tZymiVLF4wJYXIi5QrvwixNRzssk4G_vRBHrAdg4E1ddNwy9c2cZA" },
    { name: "Stickman Golf", href: "games/stickmangolf.html", img: "https://image.spreadshirtmedia.com/image-server/v1/products/T1459A839PA3861PT28D12687618W6161H10000/views/1,width=550,height=550,appearanceId=839,backgroundColor=F2F2F2/golf-stickman-sticker.webp" },
    { name: "Pandemic 2", href: "games/pandemic2.html", img: "images/pandemic2.webp" },
    { name: "Riddle School Games", href: "games/riddleschool-all-games.html", img: "https://i.ytimg.com/vi/Ls5rT-7_4d4/sddefault.jpg" },
    { name: "Cupcake 2048", href: "games/cupcake2048.html", img: "images/cupcake2048.webp" },
    { name: "Jetpack Joyride", href: "games/jetpack-joyride.html", img: "images/jetpackjoyride.webp" },
    { name: "Geometry Dash", href: "games/geodash.html", img: "images/geodash.webp" },
    { name: "Duck Life 1", href: "games/ducklife1.html", img: "images/ducklife1.webp" },
    { name: "Friday Night Funkin", href: "games/friday-night-funkin.html", img: "images/fridaynightfunkin.webp" },
    { name: "Galaga", href: "games/galaga.html", img: "images/galaga.webp" },
    { name: "Gravity Guy", href: "games/gravityguy.html", img: "images/gravityguy.webp" },
    { name: "Gun Mayhem", href: "games/gunmayhem.html", img: "images/gunmayhem.webp" },
    { name: "Gyroball", href: "games/gyroball.html", img: "images/gyroball.webp" },
    { name: "Happy Wheels", href: "games/happy-wheels.html", img: "images/happywheels.webp" },
    { name: "Henry Stickman: Full Collection", href: "games/henry-stickman.html", img: "images/henrystickman.webp" },
    { name: "Idle Shark", href: "games/idle-shark.html", img: "images/idleshark.webp" },
    { name: "Marippy", href: "games/marippy.html", img: "images/marippy.webp" },
    { name: "Minecraft Tower Defense", href: "games/minecraft-tower-defence.html", img: "images/minecrafttowerdefense.webp" },
    { name: "Minecraft Tower Defense 2", href: "games/minecraft-tower-defence-2.html", img: "images/minecrafttowerdefense2.webp" },
    { name: "Motherload", href: "games/motherload.html", img: "images/motherload.webp" },
    { name: "N Gon", href: "games/ngon.html", img: "images/ngon.webp" },
    { name: "Oiligarchy", href: "games/oiligarchy.html", img: "images/oiligarchy.webp" },
    { name: "Pacman", href: "games/pacman.html", img: "images/pacman.webp" },
    { name: "Pacxon", href: "games/pacxon.html", img: "images/pacxon.webp" },
    { name: "Quake III Arena", href: "games/quake3.html", img: "images/quake3.webp" },
    { name: "Pool", href: "games/pool.html", img: "images/pool.webp" },
    { name: "Pregnancy Test", href: "games/pregnancy-test.html", img: "images/pregnancytest.webp" },
    { name: "Shuffle", href: "games/shuffle.html", img: "images/shuffle.webp" },
    { name: "Slither.io", href: "games/slitherio.html", img: "images/slitherio.webp" },
    { name: "Snailiad", href: "games/snailiad.html", img: "images/snailiad.webp" },
    { name: "Snake", href: "games/snake.html", img: "images/snake.webp" },
    { name: "Snowline", href: "games/snowline.html", img: "images/nowline.webp" },
    { name: "Sort the Court", href: "games/sort-the-court.html", img: "images/sortthecourt.webp" },
    { name: "Spelunky", href: "games/spelunky.html", img: "images/spelunky.webp" },
    { name: "Steal This Election", href: "games/stealthiselection.html", img: "images/stealthiselection.webp" },
    { name: "Supersonic", href: "games/super-sonic.html", img: "images/supersonic.webp" },
    { name: "Super Mario 63", href: "games/supermario63.html", img: "images/supermario63.webp" },
    { name: "Swords and Sandals 2", href: "games/swords-and-sandals-2.html", img: "images/swordsandsandals2.webp" },
    { name: "Tetris", href: "games/tetris.html", img: "images/tetris.webp" },
    { name: "The Big Adventure of Owata's Life", href: "games/the-big-adventure-of-owatas-life.html", img: "images/thebigadventureofowataslife.webp" },
    { name: "The Binding of Isaac", href: "games/the-binding-of-isaac.html", img: "images/thebindingofisaac.webp" },
    { name: "Tower Blaster", href: "games/towerblaster.html", img: "images/towerblaster.webp" },
    { name: "Tower Master", href: "games/towermaster.html", img: "images/towermaster.webp" },
    { name: "World's Hardest Game", href: "games/worldshardestgame.html", img: "images/worldshardestgame.webp" },
    { name: "World's Hardest Game 2", href: "games/worldshardestgame2.html", img: "images/worldshardestgame2.webp" },
    { name: "Undertale (Demo)", href: "games/undertale(demo).html", img: "images/undertale.webp" },
    { name: "Undertale: Rejuvenation Mod", href: "games/Rejuvenation.html", img: "images/rejuvenation.webp" },
    { name: "Last Breath Trio Mod", href: "games/LastBreathTrio.html", img: "images/lastbreathtrio.webp" },
    { name: "The Final Experiment Mod", href: "games/TheFinalExperiment.html", img: "images/thefinalexperiment.webp" },
    { name: "2048 Merge Run", href: "games/2048-merge-run.html", img: "games/2048-merge-run/logo.png" },
    { name: "Build a Big Army", href: "games/build-a-big-army.html", img: "games/build-a-big-army/logo.png" },
    { name: "Build a Plane", href: "games/build-a-plane.html", img: "games/build-a-plane/logo.png" },
    { name: "Camouflage and Sniper", href: "games/camouflage-and-sniper.html", img: "images/camouflagensniper.webp" },
    { name: "Car Survival 3D", href: "games/car-survival-3d.html", img: "images/carsurvival3d.webp" },
    { name: "City Defense", href: "games/city-defense.html", img: "images/citdefense.png" },
    { name: "Clothing Shop 3D", href: "games/clothing-shop-3d.html", img: "games/clothing-shop-3d/logo.png" },
    { name: "Cool Cars Run 3D", href: "games/cool-cars-run-3d.html", img: "images/coolcarsrun3d.jpeg" },
    { name: "Crush Cars 3D", href: "games/crush-cars-3d.html", img: "images/crushcars3d.png" },
    { name: "Destiny Run 3D", href: "games/destiny-run-3d.html", img: "images/destinyrun2.webp" },
    { name: "Destroy the Car 3D", href: "games/destroy-the-car-3d.html", img: "games/destroy-the-car-3d/logo.png" },
    { name: "Diamond Seeker", href: "games/diamond-seeker.html", img: "games/diamond-seeker/logo.png" },
    { name: "Draw Joust", href: "games/draw-joust.html", img: "images/drawjoust.jpeg" },
    { name: "Evolving Bombs 3D", href: "games/evolving-bombs-3d.html", img: "games/evolving-bombs-3d/logo.png" },
    { name: "Fire and Frost Master", href: "games/fire-and-frost-master.html", img: "images/fireandfrostmaster.png" },
    { name: "Fitness Empire", href: "games/fitness-empire.html", img: "images/fitnessempiregame.avif" },
    { name: "Flick Goal", href: "games/flick-goal.html", img: "games/flick-goal/logo.png" },
    { name: "Flip Master", href: "games/flip-master.html", img: "games/flip-master/logo.png" },
    { name: "Giant Wanted", href: "games/giant-wanted.html", img: "games/giant-wanted/logo.png" },
    { name: "Gun Clone", href: "games/gun-clone.html", img: "images/gunclone.jpeg" },
    { name: "Gun Runner", href: "games/gun-runner.html", img: "games/gun-runner/logo.png" },
    { name: "High Heels", href: "games/high-heels.html", img: "images/highheels.png" },
    { name: "Kaji Run", href: "games/kaji-run.html", img: "games/kaji-run/logo.png" },
    { name: "Make a Superboat", href: "games/make-a-superboat.html", img: "games/make-a-superboat/logo.png" },
    { name: "Makeover Run", href: "games/makeover-run.html", img: "images/makeoverrun.jpeg" },
    { name: "Mega Car Jumps", href: "games/mega-car-jumps.html", img: "games/mega-car-jumps/logo.png" },
    { name: "Money Rush", href: "games/money-rush.html", img: "games/money-rush/logo.png" },
    { name: "Monster Box 3D", href: "games/monster-box-3d.html", img: "games/monster-box-3d/logo.png" },
    { name: "Office Fight", href: "games/office-fight.html", img: "games/office-fight/logo.png" },
    { name: "Robot Invasion", href: "games/robot-invasion.html", img: "games/robot-invasion/logo.png" },
    { name: "Run Rich 3D", href: "games/run-rich-3d.html", img: "games/run-rich-3d/logo.png" },
    { name: "Save P Diddy from Prison", href: "games/save-p-diddy-from-prison.html", img: "games/save-p-diddy-from-prison/logo.png" },
    { name: "Seat Jam 3D", href: "games/seat-jam-3d.html", img: "games/seat-jam-3d/logo.png" },
    { name: "Shooting Master", href: "games/shooting-master.html", img: "games/shooting-master/logo.png" },
    { name: "Supermarket 3D", href: "games/supermarket-3d.html", img: "images/supermarket3d.png" },
    { name: "Survive to Victory", href: "games/survive-to-victory.html", img: "images/survivetovictory.jpg" },
    { name: "Telekinesis Attack", href: "games/telekinesis-attack.html", img: "images/telekinesis-attack.jpeg" },
    { name: "Telekinesis Car", href: "games/telekinesis-car.html", img: "images/telekinesis-car.jpeg" },
    { name: "Telekinesis Drive", href: "games/telekinesis-drive.html", img: "games/telekinesis-drive/logo.png" },
    { name: "Telekinesis", href: "games/telekinesis.html", img: "images/telekinesis.jpeg" },
    { name: "Triple Match 3D", href: "games/triple-match-3d.html", img: "images/triplematch3d.jpeg" },
    { name: "Tug of War with Cars", href: "games/tug-of-war-with-cars.html", img: "images/tugofwarswithcars.jpg" },
    { name: "Twerk Race 3D", href: "games/twerk-race-3d.html", img: "images/twerkrace3d.png" },
    { name: "Twisted Rope 3D", href: "games/twisted-rope-3d.html", img: "games/twisted-rope-3d/logo.png" },
    { name: "Wall Crawler", href: "games/wall-crawler.html", img: "games/wall-crawler/logo.png" },
    { name: "War Regions", href: "games/war-regions.html", img: "images/warregions.png" },
    { name: "Weapon Craft Run", href: "games/weapon-craft-run.html", img: "images/weaponcraftrun.jpeg" },
    { name: "Weapon Upgrade Rush", href: "games/weapon-upgrade-rush.html", img: "images/weaponupgraderun.jpeg" },
    { name: "Wheel Scale", href: "games/wheel-scale.html", img: "images/wheelscales.jpeg" },
    { name: "Starpoly", href: "games/starpoly.html", img: "https://img.gamemonetize.com/stp68cw05n283o49a9n8qym64knqpbmz/512x384.jpg" },
    { name: "Bus School Park Driver", href: "games/bus-school-park-driver.html", img: "https://img.gamemonetize.com/i429yunzarak64517ysvdeki741nrdoc/512x384.jpg" },
    { name: "Real Driving Simulator", href: "games/real-driving-simulator.html", img: "https://img.gamemonetize.com/86nvuq9kpejinx49fv27relwo1b8ulrz/512x384.jpg" },
    { name: "Air Slip", href: "games/air-slip.html", img: "https://img.gamemonetize.com/v6hvw1trmapk48hnc7e9z9fannd7ouuz/512x384.jpg" },
    { name: "The Last Shot", href: "games/the-last-shot.html", img: "https://img.gamemonetize.com/jx55tyrf879uilkgs7zqes0u7muesrfr/512x384.jpg" },
    { name: "Mouse Raider", href: "games/mouse-raider.html", img: "https://img.gamemonetize.com/1qfjio3168bf56q7j4nvtmbsecmg8tm9/512x384.jpg" },
    { name: "PixelCraft Animal School", href: "games/pixelcraft-animal-school.html", img: "https://img.gamemonetize.com/26ep0w2hgpmy22lsygextvvxv4as2kl0/512x384.jpg" },
    { name: "Arrow Fest 3D Online", href: "games/arrow-fest-3d-online.html", img: "https://img.gamemonetize.com/1stwld5rfunzortwdpg0b7zu2wygon4p/512x384.jpg" },
    { name: "We Bare Bears Difference", href: "games/we-bare-bears-difference.html", img: "https://img.gamemonetize.com/zdri7sr13ti3ygexwlcjbwln0ycjcupb/512x384.jpg" },
    { name: "Little Princess Jigsaw", href: "games/little-princess-jigsaw.html", img: "https://img.gamemonetize.com/cjufvc54qijk666gaqk2efizy6b4565i/512x384.jpg" },
    { name: "Hotel Transylvania Coloring Book", href: "games/hotel-transylvania-coloring-book.html", img: "https://img.gamemonetize.com/hr3170u73fw7f1yr3pe1yjvplqjo3kfw/512x384.jpg" },
    { name: "Escape Mystic Castle Mobile version", href: "games/escape-mystic-castle-mobile-version.html", img: "https://img.gamemonetize.com/dpei1y1bfdd6vsgthkjwfnk7u7g0xu4s/512x384.jpg" },
    { name: "Jump Over Alphabets", href: "games/jump-over-alphabets.html", img: "https://img.gamemonetize.com/mqktfq5t3bu14251v5tjrnedhdjrhytl/512x384.jpg" },
    { name: "Jelly Matches", href: "games/jelly-matches.html", img: "https://img.gamemonetize.com/45k2hkp92lx338zqlj5m2xr3puexfduw/512x384.jpg" },
    { name: "Paperly: Paper Plane Adventure", href: "games/paperly-paper-plane-adventure.html", img: "https://img.gamemonetize.com/ga0hdulxnef9p1hkw72ci2pk44lbcdar/512x384.jpg" },
    { name: "Bridge Wars", href: "games/bridge-wars.html", img: "https://img.gamemonetize.com/wf6qo75w4eyuvylmnpezdk3ord3ajdlr/512x384.jpg" },
    { name: "Super Tank Hero", href: "games/super-tank-hero.html", img: "https://img.gamemonetize.com/0uxm1wr0oe3hjhotghpwp2w8n0tfdnkl/512x384.jpg" },
    { name: "Hide And Seek Blue Monster", href: "games/hide-and-seek-blue-monster.html", img: "https://img.gamemonetize.com/digi5xwq9xlsyolubtfl4ofqyxnc7a02/512x384.jpg" },
    { name: "Math games for Dummies", href: "games/math-games-for-dummies.html", img: "https://img.gamemonetize.com/43k8qhlegc44xa78lh8v6cdkqddqedqc/512x384.jpg" },
    { name: "Fall Guy 2024", href: "games/fall-guy-2024.html", img: "https://img.gamemonetize.com/v3yu7w2xefhhjb1aqdv7xb41t990o291/512x384.jpg" },
    { name: "2D Car Driving: Drive Safe", href: "games/2d-car-driving-drive-safe.html", img: "https://img.gamemonetize.com/vrvldrihwffzn2t7r0c6e5qzmz90d2xl/512x384.jpg" },
    { name: "Circle Of Heroes", href: "games/circle-of-heroes.html", img: "https://img.gamemonetize.com/fr5m0kur9spb79mo9mnhi9mbp4ncus2a/512x384.jpg" },
    { name: "Domino Adventure", href: "games/domino-adventure.html", img: "https://img.gamemonetize.com/xissi6tuoy9rwj54203f971u47olh4rx/512x384.jpg" },
    { name: "Purrfect Clicker", href: "games/purrfect-clicker.html", img: "https://img.gamemonetize.com/3f3q387pm95ba4tedpgs9vyokc50m5g2/512x384.jpg" },
    { name: "Juicy Tic Tac Toe Battle", href: "games/juicy-tic-tac-toe-battle.html", img: "https://img.gamemonetize.com/qld3sjsry030ic8jxwjoo08v46ceugul/512x384.jpg" },
    { name: "HookCube", href: "games/hookcube.html", img: "https://img.gamemonetize.com/gulhsbobq6o3avyywv4k41qgxkw36pvl/512x384.jpg" },
    { name: "Pull The Pin Much Money", href: "games/pull-the-pin-much-money.html", img: "https://img.gamemonetize.com/u6y73ibps2wn7w3o4z135ppn4rsrx588/512x384.jpg" },
    { name: "Noodle Stack Runner", href: "games/noodle-stack-runner.html", img: "https://img.gamemonetize.com/me10twl3ggmhi220yxqtnxgocpqdjhun/512x384.jpg" },
    { name: "Big hand", href: "games/big-hand.html", img: "https://img.gamemonetize.com/eavzi2yfqn19pwk41njc6rtfwv3z97h6/512x384.jpg" },
    { name: "Flappy Ship Classic", href: "games/flappy-ship-classic.html", img: "https://img.gamemonetize.com/1gmiifl3myqa1vce5h60q01x45l6oinb/512x384.jpg" },
    { name: "Practice On Me", href: "games/practice-on-me.html", img: "https://img.gamemonetize.com/opcw3n645043j5d1v13a7effq93p4no0/512x384.jpg" },
    { name: "RedPool Legend 2 Player", href: "games/redpool-legend-2-player.html", img: "https://img.gamemonetize.com/sjzwvzpgyoj0vj3vogehwpgxfyf3dq2i/512x384.jpg" },
    { name: "Noob the builder", href: "games/noob-the-builder.html", img: "https://img.gamemonetize.com/a3v2dofspzlvni2lpl9omcz6r0w0tpmh/512x384.jpg" },
    { name: "Balloons Park", href: "games/balloons-park.html", img: "https://img.gamemonetize.com/806sjmyu8bjoiqhqzlwh3l3ikfyjhfg9/512x384.jpg" },
    { name: "Stunt Maps", href: "games/stunt-maps.html", img: "https://img.gamemonetize.com/we3v62yymmy7l2m9yuvuxdewrro4tloo/512x384.jpg" },
    { name: "Shape Transform Blob Racing", href: "games/shape-transform-blob-racing.html", img: "https://img.gamemonetize.com/6oqz5gzl1kboj8qfz83uy2dt8tcdutkt/512x384.jpg" },
    { name: "Addition: Bird Image Uncover", href: "games/addition-bird-image-uncover.html", img: "https://img.gamemonetize.com/0svpruoyftz3vzv7kkaqlfhp02y647k8/512x384.jpg" },
    { name: "AnimalCraft Friends", href: "games/animalcraft-friends.html", img: "https://img.gamemonetize.com/sz81v16rr1h6jp61pk95gf62e7sx822u/512x384.jpg" },
    { name: "Bitcoin Millionaire", href: "games/bitcoin-millionaire.html", img: "https://img.gamemonetize.com/has0kqw18z3lb5zu4jd1v0wvvuwzzbwn/512x384.jpg" },
    { name: "Jungle Jump", href: "games/jungle-jump.html", img: "https://img.gamemonetize.com/hfjjrl9wlbbh1rbnudt1xhy6v8y91umy/512x384.jpg" },
    { name: "Real Savior", href: "games/real-savior.html", img: "https://img.gamemonetize.com/61tmgj7nz1u1741bc5k5csy3t92jyue6/512x384.jpg" },
    { name: "Watermelon Merge 3", href: "games/watermelon-merge-3.html", img: "https://img.gamemonetize.com/bc9vvvp7hi25zebwo942m98sfeot8v98/512x384.jpg" },
    { name: "Ghost Town Escape 4 - Mirrored Dimension", href: "games/ghost-town-escape-4-mirrored-dimension.html", img: "https://img.gamemonetize.com/83alolumjc1uxkn0vz2nx7oflexgnw04/512x384.jpg" },
    { name: "The Rabbit Adventure", href: "games/the-rabbit-adventure.html", img: "https://img.gamemonetize.com/safgugvb6mzict1et21wz0ztqmwr8e90/512x384.jpg" },
    { name: "Mini Games Puzzle Collection", href: "games/mini-games-puzzle-collection.html", img: "https://img.gamemonetize.com/q5rwkipcspvikwz788k56863zxabdjlg/512x384.jpg" },
    { name: "Cat Pet Doctor Dentist", href: "games/cat-pet-doctor-dentist.html", img: "https://img.gamemonetize.com/2k0wbrioi2gllnf2nns4d33n8gt6fmio/512x384.jpg" },
    { name: "Super Doctor Body Examination", href: "games/super-doctor-body-examination.html", img: "https://img.gamemonetize.com/2iwba0rqln0grbzu8wxt3pphl1yrbe9e/512x384.jpg" },
    { name: "Perfect Piano Magic", href: "games/perfect-piano-magic.html", img: "https://img.gamemonetize.com/yxvf7gwdccvrfkoykfngpnmhkjox49gr/512x384.jpg" },
    { name: "Minescraftter Two Player", href: "games/minescraftter-two-player.html", img: "https://img.gamemonetize.com/eueexa64q431mmoj8kd6wh6fxfgax0uu/512x384.jpg" },
    { name: "Candy Cat Shot", href: "games/candy-cat-shot.html", img: "https://img.gamemonetize.com/g9piog0gw7q75u64j5lo9vrdpke10tsi/512x384.jpg" },
    { name: "Connect Pipe! Color Puzzle Game", href: "games/connect-pipe-color-puzzle-game.html", img: "https://img.gamemonetize.com/nszriut9whcdc3w98wh18ls3u0qhmf7v/512x384.jpg" },
    { name: "Imposter Assassin 3D", href: "games/imposter-assassin-3d.html", img: "https://img.gamemonetize.com/kjixdc9mw89s3k1rdka4eotbmrgggvkn/512x384.jpg" },
    { name: "Brick Hit", href: "games/brick-hit.html", img: "https://img.gamemonetize.com/usdmhsnhviloqv61pmchec4hbx4p36i7/512x384.jpg" },
    { name: "Block Craft 3D School", href: "games/block-craft-3d-school.html", img: "https://img.gamemonetize.com/cfju14fi5zca7zzt1gyefjvvi2crlbst/512x384.jpg" },
    { name: "Gold Miner Tower Defense", href: "games/gold-miner-tower-defense.html", img: "https://img.gamemonetize.com/ukcyc9vpff2jus19qjkt6gbxxoyo84qw/512x384.jpg" },
    { name: "Z Machine", href: "games/z-machine.html", img: "https://img.gamemonetize.com/6pb58yxizvrukc8x8wvbf3tqnaoffbtq/512x384.jpg" },
    { name: "Cake Maker Kids Cooking", href: "games/cake-maker-kids-cooking.html", img: "https://img.gamemonetize.com/2xy063qgy3crylipep1qpyvw3gxbjzc5/512x384.jpg" },
    { name: "Nightmare Float", href: "games/nightmare-float.html", img: "https://img.gamemonetize.com/bvp3ndb3kmg2w1kky9wd4nr39105kcnr/512x384.jpg" },
    { name: "Bottle Battle", href: "games/bottle-battle.html", img: "https://img.gamemonetize.com/a7fognb5ezg1z5x7x1b23f4t6z5tk1gc/512x384.jpg" },
    { name: "Memory Exclusive", href: "games/memory-exclusive.html", img: "https://img.gamemonetize.com/s6kp2cgj3m6vuqf9o8dp2bmmrnh6ptzn/512x384.jpg" },
    { name: 'Dead Plate', href: "games/dead-plate.html", img: "games/dead-plate/icon/icon.png" },
    { name: 'The Deadseat', href: "games/deadseat.html", img: "games/deadseat/index.icon.png" },
    { name: 'DeltaTraveler', href: "games/deltatraveler.html", img: "https://img.itch.zone/aW1nLzI4NjcxNjY0LnBuZw==/original/TEvWmT.png" },
    { name: 'Do Not Take This Cat Home', href: "games/donottakethiscathome.html", img: "games/donottakethiscathome/icons/icon.png" },
    { name: 'Fears to Fathom: Home Alone', href: "games/fears-to-fathom.html", img: "https://img.itch.zone/aW1nLzY0MTY5NTgucG5n/original/U%2BD0HF.png" },
    { name: 'Getting Over It', href: "games/getting-over-it.html", img: "https://cdn.cloudflare.steamstatic.com/steam/apps/240720/header.jpg" },
    { name: 'Happy Sheepies', href: "games/happy-sheepies.html", img: "https://img.itch.zone/aW1nLzE1NzA0NDc5LnBuZw==/original/3rKBZl.png" },
    { name: 'Hotline Miami', href: "games/hotline-miami.html", img: "https://cdn.cloudflare.steamstatic.com/steam/apps/219150/header.jpg" },
    { name: 'Human Expenditure Program', href: "games/human-expenditure-program.html", img: "games/human-expenditure-program/icon/icon.png" },
    { name: 'Jelly Drift', href: "games/jelly-drift.html", img: "https://img.itch.zone/aW1hZ2UvOTU0Mzg4LzU0MTAxNDEucG5n/347x500/YY6osH.png" },
    { name: 'Karlson', href: "games/karlson.html", img: "https://cdn.cloudflare.steamstatic.com/steam/apps/1228610/header.jpg" },
    { name: 'Kindergarten', href: "games/kindergarten.html", img: "https://cdn.cloudflare.steamstatic.com/steam/apps/589590/header.jpg" },
    { name: 'Kindergarten 2', href: "games/kindergarten-2.html", img: "https://cdn.cloudflare.steamstatic.com/steam/apps/1067850/header.jpg" },
    { name: 'Lacy\'s Flash Games', href: "games/lacysflashgames.html", img: "games/lacysflashgames/Lacey's%20Flash%20Games.icon.png" },
    { name: 'Milkman Karlson', href: "games/milkman-karlson.html", img: "https://cdn.cloudflare.steamstatic.com/steam/apps/1228610/header.jpg" },
    { name: 'Minesweeper Plus', href: "games/minesweeperplus.html", img: "games/minesweeperplus/MinesweeperPlus.icon.png" },
    { name: 'OMORI', href: "games/omori-fixed.html", img: "https://cdn.cloudflare.steamstatic.com/steam/apps/1150690/header.jpg" },
    { name: 'People Playground', href: "games/people-playground.html", img: "https://cdn.cloudflare.steamstatic.com/steam/apps/1118200/header.jpg" },
    { name: 'Raft', href: "games/raft.html", img: "https://cdn.cloudflare.steamstatic.com/steam/apps/648800/header.jpg" },
    { name: 'R.E.P.O.', href: "games/repo.html", img: "https://cdn.cloudflare.steamstatic.com/steam/apps/3241660/header.jpg" },
    { name: 'SchoolBoy Runaway', href: "games/schoolboy-runaway.html", img: "https://cdn.cloudflare.steamstatic.com/steam/apps/3359320/header.jpg" },
    { name: 'Slender', href: "games/slender.html", img: "https://img.itch.zone/aW1nLzE5NTgxNDM4LmpwZw==/347x500/hgY8WP.jpg" },
    { name: 'Sonic.exe', href: "games/sonic-exe.html", img: "images/favicon-32x32.png" },
    { name: 'Speed Stars', href: "games/speed-stars.html", img: "https://img.poki-cdn.com/cdn-cgi/image/q=78,scq=50,width=314,height=314,fit=cover,f=auto/04f09e51e79fd1b6a5cc974b504d6379/speed-stars-logo.png" },
    { name: 'Tattletail', href: "games/tattletail.html", img: "https://cdn.cloudflare.steamstatic.com/steam/apps/568090/header.jpg" },
    { name: 'The Man from the Window', href: "games/the-man-in-the-window.html", img: "https://img.itch.zone/aW1hZ2UvMTUxMTk3Ni84ODE0MjM3LnBuZw==/347x500/y%2Fl0uw.png" },
    { name: 'ULTRAKILL', href: "games/ultrakill.html", img: "https://cdn.cloudflare.steamstatic.com/steam/apps/1229490/header.jpg" },
    { name: 'Undertale Yellow', href: "games/undertale-yellow.html", img: "games/undertale-yellow/favicon.png" },
    { name: 'WEBFISHING', href: "games/web-fishing.html", img: "https://cdn.cloudflare.steamstatic.com/steam/apps/3146520/header.jpg" },
    { name: 'Witch\'s Heart', href: "games/witch-heart.html", img: "games/witch-heart/games/default/Title/taitoru.png" },
    { name: 'Yandere Simulator', href: "games/yandere-simulator.html", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Logo_Yandere_Simulator.svg/250px-Logo_Yandere_Simulator.svg.png" },
    { name: 'Yume Nikki', href: "games/yume-nikki.html", img: "https://cdn.cloudflare.steamstatic.com/steam/apps/650700/header.jpg" },
    { name: 'That\'s Not My Neighbor', href: "games/thats-not-my-neighbor.html", img: "games/thats-not-my-neighbor/thats-not-my-neighbor.icon.png" },
    { name: 'Bloodmoney', href: "games/bloodmoney.html", img: "games/bloodmoney/icon/icon.png" },
    { name: 'Buckshot Roulette', href: "games/buckshot-roulette.html", img: "games/buckshot-roulette/buckshot-roulette.icon.png" },
    { name: 'Class of \'09', href: "games/class-of-09.html", img: "games/class-of-09/icons/icon.png" },
    { name: 'Amanda the Adventurer', href: "games/amanda-the-adventurer.html", img: "https://cdn.cloudflare.steamstatic.com/steam/apps/2166060/header.jpg" },
    { name: 'Andy\'s Apple Farm', href: "games/andys-apple-farm.html", img: "https://img.itch.zone/aW1nLzY3ODA0MjAucG5n/original/x3awst.png" },
    { name: 'Baldi\'s Basics Classic Remastered', href: "games/baldi-remaster.html", img: "https://img.itch.zone/aW1nLzU1NjE5MzgucG5n/original/tCxFaT.png" },
    { name: 'Bendy and the Ink Machine', href: "games/bendy.html", img: "https://cdn.cloudflare.steamstatic.com/steam/apps/622650/header.jpg" },
    { name: 'Bergentruck', href: "games/bergentruck.html", img: "games/bergentruck/BERGENTRUCK_201X.icon.png" },
];

window.SCHPLAY_GAMES.ready = true;

if (typeof document !== 'undefined') {
    const event = new CustomEvent('schplay:games-ready', {
        detail: { size: window.SCHPLAY_GAMES.list.length }
    });
    document.dispatchEvent(event);
}
