window.SCHPLAY_GAMES = window.SCHPLAY_GAMES || {};
window.SCHPLAY_GAMES.list = [
    { name: "Deep Freeze", href: "games/deep-freeze.html", img: "images/deepfreeze.webp" },
    { name: "Doodle Jump", href: "games/doodlejump.html", img: "images/doodlejump.webp" },
    { name: "Duck Life 3", href: "games/duck-life-3.html", img: "images/ducklife3.webp" },
    { name: "Duck Life 5", href: "games/duck-life-5.html", img: "images/ducklife5.webp" },
    { name: "Duck Hunt", href: "games/duckhunt.html", img: "images/duckhunt.webp" },
    { name: "Duck Life 2", href: "games/ducklife2.html", img: "images/ducklife2.webp" },
    { name: "Dune Buggy", href: "games/dunebuggy.html", img: "images/dunebuggy.webp" },
    { name: "Electric Man 2", href: "games/electric-man-2.html", img: "images/electricman2.webp" },
    { name: "Fireboy and Watergirl Fire Temple", href: "games/fireboy-and-watergirl-firetemple.html", img: "images/fireboywatergirlfiretemple.webp" },
    { name: "Flappy 2048", href: "games/flappy-2048.html", img: "images/flappy2048.webp" },
    { name: "Flappy Bird", href: "games/flappy-bird.html", img: "images/flappybird.webp" },
    { name: "Bad Time Simulator", href: "games/bad-time-simulator.html", img: "images/badtimesimulator.webp" },
    { name: "Baldi's Basics Plus", href: "games/baldi-plus.html", img: "images/baldiplus.webp" },
    { name: "Bejeweled 2", href: "games/bejeweled2.html", img: "images/bejeweled2.webp" },
    { name: "Bloxors", href: "games/bloxors.html", img: "images/bloxors.webp" },
    { name: "Cat Mario", href: "games/catmario.html", img: "images/catmario.webp" },
    { name: "Club Penguin", href: "games/clubpenguin.html", img: "images/clubpenguin.webp" },
    { name: "Curveball", href: "games/curveball.html", img: "images/curveball.webp" },
    { name: "Adastra", href: "games/adastra.html", img: "images/adastra.webp" },
    { name: "Antbuster", href: "games/antbuster.html", img: "images/antbuster.webp" },
    { name: "Arcade Wizard", href: "games/arcade-wizard.html", img: "images/arcadewizard.webp" },
    { name: "Bad Ice Cream 1", href: "games/bad-icecream-1.html", img: "images/badicecream1.webp" },
    { name: "Bad Ice Cream 2", href: "games/bad-icecream-2.html", img: "images/badicecream2.webp" },
    { name: "Bad Ice Cream 3", href: "games/bad-icecream-3.html", img: "images/badicecream3.webp" },
    { name: "Agar.io", href: "games/agario.html", img: "images/agario.webp" },
    { name: "Angry Birds Halloween", href: "games/angrybirdshalloween.html", img: "images/angrybirdshalloween.webp" },
    { name: "Ace Gangster", href: "games/acegangster.html", img: "images/acegangster.webp" },
    { name: "10 Minutes Till Dawn", href: "games/10-minutes-till-dawn.html", img: "images/10mintilldawn.webp" },
    { name: "1v1.lol", href: "games/1v1lol.html", img: "https://play-lh.googleusercontent.com/QYGRIDJbyVO7L7jH8CwiKJ4NumTGgcTVqU3ITooLWxro-eeNns1RZ0uwGGFe-r8M4co" },
    { name: "Slope", href: "games/slope.html", img: "images/slope.webp" },
    { name: "Slope 2", href: "games/slope2.html", img: "images/slope2.webp" },
    { name: "Retro Bowl [New Verison]", href: "games/retrobowl.html", img: "images/retrobowl.webp" },
    { name: "Block Blast", href: "games/blockblast.html", img: "images/blockblast.webp" },
    { name: "Idle Breakout", href: "games/idle-breakout.html", img: "images/idlebreakout.webp" },
    { name: "Gunspin", href: "games/gunspin.html", img: "images/gunspin.webp" },
    { name: "Learn To Fly", href: "games/learntofly.html", img: "games/learntofly/icon.png" },
    { name: "Learn To Fly 2", href: "games/learntofly2.html", img: "images/learntofly2.webp" },
    { name: "Learn To Fly 3", href: "games/learntofly3.html", img: "images/learntofly3.webp" },
    { name: "House Of Hazards", href: "games/houseofhazards.html", img: "images/houseofhazards.webp" },
    { name: "Hole.io", href: "games/holeio.html", img: "images/holeio.webp" },
    { name: "Cut The Rope", href: "games/cut-the-rope.html", img: "images/cuttherope.webp" },
    { name: "Tank Trouble", href: "games/tanktrouble.html", img: "images/tanktrouble.webp" },
    { name: "Drift Hunters", href: "games/drifthunters.html", img: "images/drifthunters.webp" },
    { name: "Draw The Hill", href: "games/draw-the-hill.html", img: "images/drawthehill.webp" },
    { name: "Getaway Shootout", href: "games/getaway-shootout.html", img: "images/getawayshootout.webp" },
    { name: "Crossy Road", href: "games/crossyroad.html", img: "images/crossyroad.webp" },
    { name: "Rooftop Sniper", href: "games/rooftopsnipers.html", img: "images/rooftopsnipers.webp" },
    { name: "Boxing Random", href: "games/boxingrandom.html", img: "images/boxingrandom.webp" },
    { name: "Adventure Capitalist", href: "games/adventurecapitalist.html", img: "images/adventurecapitalist.webp" },
    { name: "Hide & Smash", href: "games/hideandsmash.html", img: "images/hideandsmash.webp" },
    { name: "MonkeyMart", href: "games/monkey-mart.html", img: "images/monkeymart.webp" },
    { name: "Retro Bowl College FIXED!", href: "games/rb-college.html", img: "images/retrobowlcollege.webp" },
    { name: "Minecraft (Eagler)", href: "games/minecraft.html", img: "images/mc.webp" },
    { name: "Bloons TD5", href: "games/bloonstd5.html", img: "images/btd5.webp" },
    { name: "Mr Mine", href: "games/mrmine.html", img: "images/mrmine.webp" },
    { name: "Run 2", href: "games/run2.html", img: "images/run2.webp" },
    { name: "Run 3", href: "games/run3.html", img: "images/run3.webp" },
    { name: "Spend Elon's Money", href: "games/spending-elonmusk-money.html", img: "images/elonmusk.webp" },
    { name: "Plants V Zombies (Full)", href: "games/pvz.html", img: "images/pvz.webp" },
    { name: "Mine Sweeper", href: "games/minesweeper.html", img: "images/minesweeper.webp" },
    { name: "Pizza Tower", href: "games/pizzatower.html", img: "images/pizzatower.webp" },
    { name: "Pixel Gun", href: "games/pixelgun.html", img: "images/pixelgun.webp" },
    { name: "Google Snake", href: "games/googlesnake.html", img: "images/googlesnake.webp" },
    { name: "OVO", href: "games/ovo.html", img: "images/ovo.webp" },
    { name: "Basketball Stars", href: "games/basketballstars.html", img: "images/basketballstars.webp" },
    { name: "Stacktris", href: "games/stacktris.html", img: "images/stacktris.webp" },
    { name: "FNAF", href: "games/fnaf.html", img: "images/fnaf.webp" },
    { name: "DBZ Devolution", href: "games/dbz.html", img: "images/dbz.webp" },
    { name: "Drive Mad", href: "games/drivemad.html", img: "images/drivemad.webp" },
    { name: "Papa's Games", href: "games/papas-games.html", img: "images/papasgame.webp" },
    { name: "Stickman Games", href: "games/henry-stickman.html", img: "https://cdn2.steamgriddb.com/icon/9f61408e3afb633e50cdf1b20de6f466.png" },
    { name: "Vex's Games", href: "games/vex.html", img: "https://play-lh.googleusercontent.com/0OnVFzHIMuLLeMjvACoNzxRbungfOH1zH4hUWQnIg5KfM2va_mFssFuRGq26WqWA" },
    { name: "2048", href: "games/2048.html", img: "images/2048.webp" },
    { name: "Paper.io 2", href: "games/paperio2.html", img: "images/paperio2.webp" },
    { name: "1", href: "games/2048.html", img: "images/2048_logo.svg.png" },
    { name: "Subway Surfers", href: "games/subwaysurfer.html", img: "https://img.poki.com/cdn-cgi/image/quality=78,width=314,height=314,fit=cover,f=auto/81a0a3f18cf0ee129e56edb50fc52c3b.png" },
    { name: "Soccer Random", href: "games/soccer-random.html", img: "https://play-lh.googleusercontent.com/G1PIlb6HWKSaDre0XpUcmKGps9T4iamsSlwrogB3EJzYv4bz0M2am4D17MtGzndaOOU" },
    { name: "MotoX3M Games", href: "games/motox3m.html", img: "images/motocross.webp" },
    { name: "CSGO Case Opener", href: "games/csgo-clicker.html", img: "images/csgoclicker.webp" },
    { name: "Crossy Road", href: "games/crossyroad.html", img: "https://upload.wikimedia.org/wikipedia/en/7/71/Crossy_Road_icon.jpeg" },
    { name: "Temple Run 2", href: "games/templerun2.html", img: "https://play-lh.googleusercontent.com/go4XqS4mYs-G2tZymiVLF4wJYXIi5QrvwixNRzssk4G_vRBHrAdg4E1ddNwy9c2cZA" },
    { name: "Stickman Golf", href: "games/stickmangolf.html", img: "https://image.spreadshirtmedia.com/image-server/v1/products/T1459A839PA3861PT28D12687618W6161H10000/views/1,width=550,height=550,appearanceId=839,backgroundColor=F2F2F2/golf-stickman-sticker.webp" },
    { name: "Pandemic 2", href: "games/pandemic2.html", img: "images/pandemic2.webp" },
    { name: "Riddle School Games", href: "games/riddleschool-all-games.html", img: "https://i.ytimg.com/vi/Ls5rT-7_4d4/sddefault.jpg" },
    { name: "Cupcake 2048", href: "games/cupcake2048.html", img: "images/cupcake2048.webp" },
    { name: "Jetpack Joyride", href: "games/jetpack-joyride.html", img: "images/jetpackjoyride.webp" },
    { name: "Geometry Dash", href: "games/geodash.html", img: "images/geodash.webp" },
    { name: "Duck Life 1", href: "games/ducklife1.html", img: "images/ducklife1.webp" },
    { name: "Friday Night Funkin", href: "games/friday-night-funkin.html", img: "images/fridaynightfunkin.webp" },
    { name: "Galaga", href: "games/galaga.html", img: "images/galaga.webp" },
    { name: "Gravity Guy", href: "games/gravityguy.html", img: "images/gravityguy.webp" },
    { name: "Gun Mayhem", href: "games/gunmayhem.html", img: "images/gunmayhem.webp" },
    { name: "Gyroball", href: "games/gyroball.html", img: "images/gyroball.webp" },
    { name: "Happy Wheels", href: "games/happy-wheels.html", img: "images/happywheels.webp" },
    { name: "Henry Stickman: Full Collection", href: "games/henry-stickman.html", img: "images/henrystickman.webp" },
    { name: "Idle Shark", href: "games/idle-shark.html", img: "images/idleshark.webp" },
    { name: "Marippy", href: "games/marippy.html", img: "images/marippy.webp" },
    { name: "Minecraft Tower Defense", href: "games/minecraft-tower-defence.html", img: "images/minecrafttowerdefense.webp" },
    { name: "Minecraft Tower Defense 2", href: "games/minecraft-tower-defence-2.html", img: "images/minecrafttowerdefense2.webp" },
    { name: "Motherload", href: "games/motherload.html", img: "images/motherload.webp" },
    { name: "N Gon", href: "games/ngon.html", img: "images/ngon.webp" },
    { name: "Oiligarchy", href: "games/oiligarchy.html", img: "images/oiligarchy.webp" },
    { name: "Pacman", href: "games/pacman.html", img: "images/pacman.webp" },
    { name: "Pacxon", href: "games/pacxon.html", img: "images/pacxon.webp" },
    { name: "Quake III Arena", href: "games/quake3.html", img: "images/quake3.webp" },
    { name: "Pool", href: "games/pool.html", img: "images/pool.webp" },
    { name: "Pregnancy Test", href: "games/pregnancy-test.html", img: "images/pregnancytest.webp" },
    { name: "Shuffle", href: "games/shuffle.html", img: "images/shuffle.webp" },
    { name: "Slither.io", href: "games/slitherio.html", img: "images/slitherio.webp" },
    { name: "Snailiad", href: "games/snailiad.html", img: "images/snailiad.webp" },
    { name: "Snake", href: "games/snake.html", img: "images/snake.webp" },
    { name: "Snowline", href: "games/snowline.html", img: "images/nowline.webp" },
    { name: "Sort the Court", href: "games/sort-the-court.html", img: "images/sortthecourt.webp" },
    { name: "Spelunky", href: "games/spelunky.html", img: "images/spelunky.webp" },
    { name: "Steal This Election", href: "games/stealthiselection.html", img: "images/stealthiselection.webp" },
    { name: "Supersonic", href: "games/super-sonic.html", img: "images/supersonic.webp" },
    { name: "Super Mario 63", href: "games/supermario63.html", img: "images/supermario63.webp" },
    { name: "Swords and Sandals 2", href: "games/swords-and-sandals-2.html", img: "images/swordsandsandals2.webp" },
    { name: "Tetris", href: "games/tetris.html", img: "images/tetris.webp" },
    { name: "The Big Adventure of Owata's Life", href: "games/the-big-adventure-of-owatas-life.html", img: "images/thebigadventureofowataslife.webp" },
    { name: "The Binding of Isaac", href: "games/the-binding-of-isaac.html", img: "images/thebindingofisaac.webp" },
    { name: "Tower Blaster", href: "games/towerblaster.html", img: "images/towerblaster.webp" },
    { name: "Tower Master", href: "games/towermaster.html", img: "images/towermaster.webp" },
    { name: "World's Hardest Game", href: "games/worldshardestgame.html", img: "images/worldshardestgame.webp" },
    { name: "World's Hardest Game 2", href: "games/worldshardestgame2.html", img: "images/worldshardestgame2.webp" },
    { name: "Undertale (Demo)", href: "games/undertale(demo).html", img: "images/undertale.webp" },
    { name: "Undertale: Rejuvenation Mod", href: "games/Rejuvenation.html", img: "images/rejuvenation.webp" },
    { name: "Last Breath Trio Mod", href: "games/LastBreathTrio.html", img: "images/lastbreathtrio.webp" },
    { name: "The Final Experiment Mod", href: "games/TheFinalExperiment.html", img: "images/thefinalexperiment.webp" }
];

window.SCHPLAY_GAMES.ready = true;

if (typeof document !== 'undefined') {
    const event = new CustomEvent('schplay:games-ready', {
        detail: { size: window.SCHPLAY_GAMES.list.length }
    });
    document.dispatchEvent(event);
}
